version: '3'
services:
  career-scraper:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/career_scraper.Dockerfile
    command: poetry run python3 src/career_scraper.py
    depends_on:
      redis:
        condition:
          service_healthy
    volumes:
      - type: bind
        source: logs
        target: /app/logs
      - type: bind
        source: data
        target: /app/data
  scraper:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/scraper.Dockerfile
    command: poetry run python3 src/scraper.py
    depends_on:
      redis:
        condition:
          service_healthy
    volumes:
      - type: bind
        source: logs
        target: /app/logs
      - type: bind
        source: data
        target: /app/data
  monitor:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/monitor.Dockerfile
    command: poetry run python3 src/monitor.py
    depends_on:
      redis:
        condition:
          service_healthy
    volumes:
      - type: bind
        source: logs
        target: /app/logs
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - type: bind
        source: logs
        target: /app/logs
      - type: bind
        source: config
        target: /app/config
    command: poetry run python3 src/crawler.py
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      redis:
        condition:
          service_healthy
  redis:
    image: redis
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - redis:/redis
volumes:
  redis: