version: '3'
services:
  scraper:
    build:
      context: .
      dockerfile: scraper.Dockerfile
    command: poetry run python3 scraper.py
    depends_on:
      - redis
      - app
    volumes:
      - type: bind
        source: data
        target: /app/data
  monitor:
    build:
      context: .
      dockerfile: monitor.Dockerfile
    command: poetry run python3 monitor.py
    depends_on:
      - redis
    volumes:
      - type: bind
        source: data
        target: /app/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: data
        target: /app/data
    command: poetry run python3 main.py
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - ./redis:/redis