version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: data
        target: /app/data
    command: poetry run python3 main.py
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - ./redis:/redis